// Re-downloads Inter into assets/fonts/.
//
// The site self-hosts its typeface. A page whose argument is that Vatulo does
// not hand your data to anyone would be a poor place to make every visitor
// fetch a font from a third party in order to read that sentence — and under
// Law 25 the list of who receives visitor data is not a detail.
//
// Latin and latin-ext only: the documents carry French accents (Montréal,
// Commission d'accès), and the other five subsets are twenty-five files that
// would never be requested.
//
// The output is committed, so this only needs running to change weights or to
// pick up a new release of Inter.
//
//   node tools/fetch-fonts.mjs
//
import { writeFileSync } from 'node:fs';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Google serves TTF to clients it does not recognise as woff2-capable, so the
// user agent above is load-bearing rather than decoration.
const API = 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap';

const WANTED = /^\/\*\s*(latin|latin-ext)\s*\*\//;

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();

let out = '/* Inter, self-hosted. Generated by tools/fetch-fonts.mjs. */\n';
let count = 0;

for (const block of css.split('/*').slice(1).map((b) => '/*' + b)) {
  if (!WANTED.test(block)) continue;

  const weight = block.match(/font-weight:\s*(\d+)/)[1];
  const subset = block.match(WANTED)[1];
  const remote = block.match(/url\((https:[^)]+\.woff2)\)/)[1];
  const name = `inter-${weight}-${subset}.woff2`;

  const bytes = Buffer.from(
    await (await fetch(remote, { headers: { 'User-Agent': UA } })).arrayBuffer(),
  );
  writeFileSync(`assets/fonts/${name}`, bytes);
  count++;

  out += block.replace(/url\(https:[^)]+\.woff2\)/, `url(./${name})`).trimEnd() + '\n';
}

writeFileSync('assets/fonts/inter.css', out);
console.log(`  ok    ${count} font files -> assets/fonts/`);
